// ----------------------------------------------- what is this routing file -----------------------------------------------

//The layout file is used to define a layout in your Next.js application. A root layout is the top-most layout in the root app directory. It is used to define the <html> and <body> tags and other globally shared UI.
//It defines how your app’s HTML structure and consistent elements are rendered. Without it, Next.js wouldn’t know what your root document looks like — it’s sort of like index.html in plain React apps.





import { Geist, Geist_Mono } from "next/font/google"; //Imports two Google fonts using Next.js’s built-in font optimization
import "./globals.css";                               //Imports a global stylesheet (globals.css) that applies styles to your whole app

const geistSans = Geist({                             //This defines custom CSS variables for the two fonts
  variable: "--font-geist-sans",                      //these variables are applied to the <body> so you can use them globally via CSS.
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {                             //This is a Next.js 13+ feature that lets you define metadata like <title>, <meta> tags, description, and more. Next.js automatically injects this into the HTML head — you don’t need to manually write <head> tags.
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {    //This is the root layout component. Layout components should accept and use a children prop. During rendering, children will be populated with the route segments the layout is wrapping. These will primarily be the component of a child Layout (if it exists) or Page, but could also be other special files like Loading or Error when applicable. It defines your global HTML structure (<html> and <body> tags).
  return (                                            //It receives { children } — this represents whatever page or nested layout is being rendered.
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} //It applies the fonts and antialiased (a CSS smoothing class from Tailwind) to the body.
      >
        {children}                                                            
      </body>                                                                 
    </html>
  );                                                  //It wraps everything that shows up on the screen.
}
