'use client';
import React, {useState} from 'react';
import { useSearchParams } from "next/navigation";
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Box, Typography, Button, FormControl, InputLabel, Select, MenuItem, } from '@mui/material';

// Reusable header cell
const HeaderCell = ({ children, sx, typographySx, boxProps, ...props }) => (
  <TableCell sx={{ border: '1px solid #000', padding: '4px 6px', ...sx }} {...props}>
    <Box display="flex" justifyContent="center" alignItems="center" {...boxProps}>
      <Typography sx={{ fontSize: 8, whiteSpace: 'nowrap', fontWeight: 'bold', ...typographySx }}>
        {children}
      </Typography>
    </Box>
  </TableCell>
);

const AccountListReport = React.forwardRef(function AccountListReport({ rows = [
  {
    RecordNo: 1,
    CalcLevel: 1,
    AccTa2MST: "10",
    AccTa1MST: "01",
    AccMoeMST: "0001",
    AccKolMST: "1000",
    AccName: "نقد و بانک",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 5,
    RcpFlgMST: "A12",
    DteFlgMST: "1403/02/01",
    CryFlgMST: "IRT",
    Center1Name: "مرکز تهران",
    ProjectName: "پروژه مرکزی",
    Center2Name: "مرکز 2 - شمال",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 3,
    CalcLevel: 1,
    AccTa2MST: "12",
    AccTa1MST: "09",
    AccMoeMST: "0011",
    AccKolMST: "3000",
    AccName: "درآمد خدمات",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 11,
    RcpFlgMST: "C17",
    DteFlgMST: "1403/05/22",
    CryFlgMST: "EUR",
    Center1Name: "مرکز مشهد",
    ProjectName: "پروژه فروش",
    Center2Name: "مرکز 2 - شرق",
  },
  {
    RecordNo: 4,
    CalcLevel: 3,
    AccTa2MST: "05",
    AccTa1MST: "03",
    AccMoeMST: "0044",
    AccKolMST: "4000",
    AccName: "موجودی کالا",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 7,
    RcpFlgMST: "D45",
    DteFlgMST: "1402/12/02",
    CryFlgMST: "IRT",
    Center1Name: "مرکز تبریز",
    ProjectName: "پروژه انبار",
    Center2Name: "مرکز 2 - غرب",
  },
  {
    RecordNo: 5,
    CalcLevel: 2,
    AccTa2MST: "03",
    AccTa1MST: "02",
    AccMoeMST: "0100",
    AccKolMST: "2100",
    AccName: "حقوق و دستمزد",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 4,
    RcpFlgMST: "E33",
    DteFlgMST: "1403/03/10",
    CryFlgMST: "USD",
    Center1Name: "مرکز اصفهان",
    ProjectName: "پروژه منابع انسانی",
    Center2Name: "مرکز 2 - مرکزی",
  },
  {
    RecordNo: 6,
    CalcLevel: 1,
    AccTa2MST: "07",
    AccTa1MST: "06",
    AccMoeMST: "0900",
    AccKolMST: "5000",
    AccName: "دارایی ثابت",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 1,
    RcpFlgMST: "F01",
    DteFlgMST: "1401/11/15",
    CryFlgMST: "IRT",
    Center1Name: "مرکز اهواز",
    ProjectName: "پروژه ساختمان",
    Center2Name: "مرکز 2 - جنوب غرب",
  },
  {
    RecordNo: 7,
    CalcLevel: 3,
    AccTa2MST: "15",
    AccTa1MST: "01",
    AccMoeMST: "0500",
    AccKolMST: "6000",
    AccName: "وام بلندمدت",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 8,
    RcpFlgMST: "G88",
    DteFlgMST: "1403/04/12",
    CryFlgMST: "EUR",
    Center1Name: "مرکز کرج",
    ProjectName: "پروژه وام‌ها",
    Center2Name: "مرکز 2 - البرز",
  },
  {
    RecordNo: 8,
    CalcLevel: 2,
    AccTa2MST: "14",
    AccTa1MST: "09",
    AccMoeMST: "0220",
    AccKolMST: "7100",
    AccName: "مالیات",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 3,
    RcpFlgMST: "H41",
    DteFlgMST: "1403/06/05",
    CryFlgMST: "IRT",
    Center1Name: "مرکز قم",
    ProjectName: "پروژه مالیات",
    Center2Name: "مرکز 2 - قم",
  },
  {
    RecordNo: 9,
    CalcLevel: 1,
    AccTa2MST: "04",
    AccTa1MST: "08",
    AccMoeMST: "0175",
    AccKolMST: "8000",
    AccName: "سرمایه",
    AccTypMST: "اصلی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 6,
    RcpFlgMST: "I92",
    DteFlgMST: "1403/07/14",
    CryFlgMST: "USD",
    Center1Name: "مرکز یزد",
    ProjectName: "پروژه سرمایه گذاری",
    Center2Name: "مرکز 2 - یزد",
  },
  {
    RecordNo: 10,
    CalcLevel: 2,
    AccTa2MST: "02",
    AccTa1MST: "01",
    AccMoeMST: "0020",
    AccKolMST: "9000",
    AccName: "وجه نقد",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 9,
    RcpFlgMST: "J29",
    DteFlgMST: "1403/02/20",
    CryFlgMST: "IRT",
    Center1Name: "مرکز کرمان",
    ProjectName: "پروژه نقدینگی",
    Center2Name: "مرکز 2 - جنوب شرق",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 1,
    CalcLevel: 1,
    AccTa2MST: "10",
    AccTa1MST: "01",
    AccMoeMST: "0001",
    AccKolMST: "1000",
    AccName: "نقد و بانک",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 5,
    RcpFlgMST: "A12",
    DteFlgMST: "1403/02/01",
    CryFlgMST: "IRT",
    Center1Name: "مرکز تهران",
    ProjectName: "پروژه مرکزی",
    Center2Name: "مرکز 2 - شمال",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 3,
    CalcLevel: 1,
    AccTa2MST: "12",
    AccTa1MST: "09",
    AccMoeMST: "0011",
    AccKolMST: "3000",
    AccName: "درآمد خدمات",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 11,
    RcpFlgMST: "C17",
    DteFlgMST: "1403/05/22",
    CryFlgMST: "EUR",
    Center1Name: "مرکز مشهد",
    ProjectName: "پروژه فروش",
    Center2Name: "مرکز 2 - شرق",
  },
  {
    RecordNo: 4,
    CalcLevel: 3,
    AccTa2MST: "05",
    AccTa1MST: "03",
    AccMoeMST: "0044",
    AccKolMST: "4000",
    AccName: "موجودی کالا",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 7,
    RcpFlgMST: "D45",
    DteFlgMST: "1402/12/02",
    CryFlgMST: "IRT",
    Center1Name: "مرکز تبریز",
    ProjectName: "پروژه انبار",
    Center2Name: "مرکز 2 - غرب",
  },
  {
    RecordNo: 5,
    CalcLevel: 2,
    AccTa2MST: "03",
    AccTa1MST: "02",
    AccMoeMST: "0100",
    AccKolMST: "2100",
    AccName: "حقوق و دستمزد",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 4,
    RcpFlgMST: "E33",
    DteFlgMST: "1403/03/10",
    CryFlgMST: "USD",
    Center1Name: "مرکز اصفهان",
    ProjectName: "پروژه منابع انسانی",
    Center2Name: "مرکز 2 - مرکزی",
  },
  {
    RecordNo: 6,
    CalcLevel: 1,
    AccTa2MST: "07",
    AccTa1MST: "06",
    AccMoeMST: "0900",
    AccKolMST: "5000",
    AccName: "دارایی ثابت",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 1,
    RcpFlgMST: "F01",
    DteFlgMST: "1401/11/15",
    CryFlgMST: "IRT",
    Center1Name: "مرکز اهواز",
    ProjectName: "پروژه ساختمان",
    Center2Name: "مرکز 2 - جنوب غرب",
  },
  {
    RecordNo: 7,
    CalcLevel: 3,
    AccTa2MST: "15",
    AccTa1MST: "01",
    AccMoeMST: "0500",
    AccKolMST: "6000",
    AccName: "وام بلندمدت",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 8,
    RcpFlgMST: "G88",
    DteFlgMST: "1403/04/12",
    CryFlgMST: "EUR",
    Center1Name: "مرکز کرج",
    ProjectName: "پروژه وام‌ها",
    Center2Name: "مرکز 2 - البرز",
  },
  {
    RecordNo: 8,
    CalcLevel: 2,
    AccTa2MST: "14",
    AccTa1MST: "09",
    AccMoeMST: "0220",
    AccKolMST: "7100",
    AccName: "مالیات",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 3,
    RcpFlgMST: "H41",
    DteFlgMST: "1403/06/05",
    CryFlgMST: "IRT",
    Center1Name: "مرکز قم",
    ProjectName: "پروژه مالیات",
    Center2Name: "مرکز 2 - قم",
  },
  {
    RecordNo: 9,
    CalcLevel: 1,
    AccTa2MST: "04",
    AccTa1MST: "08",
    AccMoeMST: "0175",
    AccKolMST: "8000",
    AccName: "سرمایه",
    AccTypMST: "اصلی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "دارد",
    AmtFlgMST: 6,
    RcpFlgMST: "I92",
    DteFlgMST: "1403/07/14",
    CryFlgMST: "USD",
    Center1Name: "مرکز یزد",
    ProjectName: "پروژه سرمایه گذاری",
    Center2Name: "مرکز 2 - یزد",
  },
  {
    RecordNo: 10,
    CalcLevel: 2,
    AccTa2MST: "02",
    AccTa1MST: "01",
    AccMoeMST: "0020",
    AccKolMST: "9000",
    AccName: "وجه نقد",
    AccTypMST: "اصلی",
    CanBeArticled: "بلی",
    AccKndMST: "بدهکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 9,
    RcpFlgMST: "J29",
    DteFlgMST: "1403/02/20",
    CryFlgMST: "IRT",
    Center1Name: "مرکز کرمان",
    ProjectName: "پروژه نقدینگی",
    Center2Name: "مرکز 2 - جنوب شرق",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
    {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
  {
    RecordNo: 2,
    CalcLevel: 2,
    AccTa2MST: "11",
    AccTa1MST: "05",
    AccMoeMST: "0032",
    AccKolMST: "2000",
    AccName: "هزینه‌های اداری",
    AccTypMST: "فرعی",
    CanBeArticled: "خیر",
    AccKndMST: "بستانکار",
    BudFlgMST: "ندارد",
    AmtFlgMST: 2,
    RcpFlgMST: "B22",
    DteFlgMST: "1403/01/12",
    CryFlgMST: "USD",
    Center1Name: "مرکز شیراز",
    ProjectName: "پروژه مالی",
    Center2Name: "مرکز 2 - جنوب",
  },
] }, ref) {

  // Safe localStorage reads
  let company = '';
  let Name = '';
  try {
    company = JSON.parse(localStorage.getItem('reuser'))?.find((i) => i.Setting_KeyRUS === 'databaseName')?.Setting_Value ?? '';
    Name = JSON.parse(localStorage.getItem('user'))?.Name ?? '';
  } catch (e) {}

  function getCurrentTime() {
    return new Date().toLocaleTimeString('fa-IR', { hour12: false });
  }
  function getCurrentDate() {
    return new Date().toLocaleDateString('fa-IR');
  }

  const infoItems = [
    ['نام کاربر:', Name],
    ['تاریخ:', getCurrentDate()],
    ['ساعت:', getCurrentTime()],
  ];

  const query = useSearchParams();
  const size = query.get("size") || "A4";

  const [printSize, setPrintSize] = useState( size || "A4");

  // Page sizes
  const pageSize = [
    { name: "A5", rows: 9, width: 559, height: 794 },
    { name: "A4", rows: 20, width: 794, height: 1123 },
    { name: "A3", rows: 31, width: 1123, height: 1587 },
    { name: "Executive", rows: 17, width: 698, height: 1014 },
    { name: "Legal", rows: 25, width: 816, height: 1350 },
    { name: "Tabloid", rows: 32, width: 1056, height: 1632 },
    { name: "Letter", rows: 18, width: 816, height: 1056 },
    { name: "B4 (JIS)", rows: 26, width: 974, height: 1375 },
    { name: "B5 (JIS)", rows: 16, width: 689, height: 974 },
    { name: "Envelope #10", rows: 16, width: 396, height: 912 },
    { name: "Envelope Monarch", rows: 11, width: 372, height: 720 },
  ];

  const selected = pageSize.find(p => p.name === size) || pageSize[1];


  const rowsPerPage = Number(selected.rows);
  const pageWidth = selected.width;
  const pageHeight = selected.height;

  // Manual pagination
  const pages = [];
  for (let i = 0; i < rows.length; i += rowsPerPage) {
    pages.push(rows.slice(i, i + rowsPerPage));
  }
  const totalPages = pages.length;

  const toPersianDigits = (num) => num.toString().replace(/\d/g, d => "۰۱۲۳۴۵۶۷۸۹"[d]);

  return (
    <>
      {/* PRINT CSS */}
      <style jsx global>{`
        @page {
          size: ${pageWidth}px ${pageHeight}px;
          margin: 10mm;
        }

        @media print {

          .page {
            width: ${pageWidth}px;
            min-height: ${pageHeight}px;
            page-break-after: always;
            position: relative;
          }

          .page:last-child {
            page-break-after: avoid !important;
            break-after: avoid !important;
          }
          .no-print { display: none; }
        }
      `}</style>

      <div ref={ref} dir="rtl">

        {/* Print button */}
        <Box className="no-print" sx={{ textAlign: "center", py: 2, display: "flex", flexDirection: "row", px: "20px", gap: 2}}>
          <Button variant="contained" sx={{ bgcolor: "#00000085", }} onClick={() => window.print()}>
            Print
          </Button>
        {/* Page size dropdown */}
        <FormControl fullWidth>
          <InputLabel>Page Size</InputLabel>
          <Select
            label="Page Size"
            value={printSize}
            onChange={(e) => {const newSize = e.target.value;
              setPrintSize(newSize);
              window.history.pushState({}, "", `/print?size=${newSize}`);
            }}
          >
            {pageSize.map((p) => (
              <MenuItem key={p.name} value={p.name}>{p.name}</MenuItem>
            ))}
          </Select>
        </FormControl>
        </Box>

        {/* RENDER EACH PAGE */}
        {pages.map((pageRows, pageIndex) => (
          <div 
            key={pageIndex} 
            className="page"
            style={{
              width: pageWidth,
              minHeight: pageHeight - 75,
              paddingLeft: "75px",
              paddingRight: "0px",
              boxSizing: "border-box",
              display: "flex",
              justifyContent: "center"
            }}
          >
            <TableContainer component={Paper} sx={{ borderRadius: 0, overflow: "hidden"}}>
              <Table size="small" sx={{ tableLayout: "fixed", width: "100%"}}>
                {/* ✅ Define column widths once here */}
                  <colgroup>
                    <col style={{ width: "3%" }} />   {/* ردیف */}
                    <col style={{ width: "4.9%" }} />   {/* سطح */}
                    <col style={{ width: "3%" }} />     {/* ت1 */}
                    <col style={{ width: "3%" }} />     {/* ت2 */}
                    <col style={{ width: "3%" }} />     {/* معین */}
                    <col style={{ width: "3%" }} />     {/* کل */}
                    <col style={{ width: "16%" }} />  {/* نام حساب */}
                    <col style={{ width: "4.9%" }} />   {/* نوع */}
                    <col style={{ width: "4.9%" }} />   {/* جزء */}
                    <col style={{ width: "6.6%" }} />   {/* ماهيت مانده */}
                    <col style={{ width: "6.6%" }} />   {/* ماهيت بودجه */}
                    <col style={{ width: "3.3%" }} />   {/* تعداد */}
                    <col style={{ width: "4.9%" }} />   {/* شرح تعداد */}
                    <col style={{ width: "4.9%" }} />   {/* شماره عطف */}
                    <col style={{ width: "4.9%" }} />   {/* تاريخ عطف */}
                    <col style={{ width: "4.9%" }} />   {/* نوع ارز */}
                    <col style={{ width: "5%" }} />   {/* مرکز هزینه */}
                    <col style={{ width: "5%" }} />   {/* مرکز1 */}
                  </colgroup>

                {/* Top info block */}
                <TableHead>
                  <TableRow>
                    <TableCell colSpan={18} sx={{ border: "1px solid #000", p: 0 }}>
                      <Box display="flex" justifyContent="space-between" alignItems="center" py={2}>

                        <Box flex={1} />

                        <Box flex={1} textAlign="center">
                          <Typography sx={{ fontSize: 16, fontWeight: "bold" }}>{company}</Typography>
                          <Typography sx={{ fontSize: 12, fontWeight: "bold" }}>فهرست حساب</Typography>
                        </Box>

                        <Box flex={1} display="flex" flexDirection="column" alignItems="flex-end" gap={1}>
                          {infoItems.map(([label, value]) => (
                            <Box key={label} display="flex" width="40%" justifyContent="space-between">
                              <Typography sx={{ fontSize: 8 }}>{label}</Typography>
                              <Typography sx={{ fontSize: 8, pl: "2px" }}>{value}</Typography>
                            </Box>
                          ))}

                          <Box display="flex" justifyContent="space-between" flexDirection="row" width="40%">
                              <Typography sx={{ fontSize: 8 }}>صفحه:</Typography>
                              <Typography sx={{ fontSize: 8, pl: "2px"}}>{toPersianDigits(pageIndex + 1)} از {toPersianDigits(totalPages)}</Typography>
                          </Box>
                        </Box>
                      </Box>
                    </TableCell>
                  </TableRow>

                  {/* Column headers */}
                  <TableRow>
                    <HeaderCell rowSpan={2}>ردیف</HeaderCell>
                    <HeaderCell rowSpan={2}>سطح</HeaderCell>
                    <HeaderCell colSpan={4}>کد حساب</HeaderCell>
                    <HeaderCell rowSpan={2}>نام حساب</HeaderCell>
                    <HeaderCell rowSpan={2}>نوع</HeaderCell>
                    <HeaderCell rowSpan={2}>جزء</HeaderCell>
                    <HeaderCell rowSpan={2}>ماهيت مانده</HeaderCell>
                    <HeaderCell rowSpan={2}>ماهيت بودجه</HeaderCell>
                    <HeaderCell rowSpan={2}>تعداد</HeaderCell>
                    <HeaderCell rowSpan={2}>شرح تعداد</HeaderCell>
                    <HeaderCell rowSpan={2}>شماره عطف</HeaderCell>
                    <HeaderCell rowSpan={2}>تاريخ عطف</HeaderCell>
                    <HeaderCell rowSpan={2}>نوع ارز</HeaderCell>
                    <HeaderCell>مرکز هزینه</HeaderCell>
                    <HeaderCell>مرکز1</HeaderCell>
                  </TableRow>

                  <TableRow>
                    {['ت1','ت2','معین','کل'].map(t => (
                      <HeaderCell key={t}>{t}</HeaderCell>
                    ))}
                    <HeaderCell>پروژه</HeaderCell>
                    <HeaderCell>مرکز2</HeaderCell>
                  </TableRow>
                </TableHead>

                {/* PAGE BODY */}
                <TableBody>
                  {pageRows.map((row, idx) => (
                    <React.Fragment key={idx}>
                      <TableRow>
                        <HeaderCell rowSpan={2}>{row.RecordNo}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.CalcLevel}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccTa2MST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccTa1MST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccMoeMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccKolMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccName}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccTypMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.CanBeArticled}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AccKndMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.BudFlgMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.AmtFlgMST}</HeaderCell>
                        <HeaderCell rowSpan={2}></HeaderCell>
                        <HeaderCell rowSpan={2}>{row.RcpFlgMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.DteFlgMST}</HeaderCell>
                        <HeaderCell rowSpan={2}>{row.CryFlgMST}</HeaderCell>
                        <HeaderCell>{row.RcpFlgMST}</HeaderCell>
                        <HeaderCell>{row.Center1Name}</HeaderCell>
                      </TableRow>

                      <TableRow>
                        <HeaderCell>{row.ProjectName}</HeaderCell>
                        <HeaderCell>{row.Center2Name}</HeaderCell>
                      </TableRow>
                    </React.Fragment>
                  ))}
                </TableBody>

              </Table>
            </TableContainer>
          </div>
        ))}

      </div>
    </>
  );
});

export default AccountListReport;
